### PR TITLE
now more than 2 users can join the room

### PR DESCRIPTION
**Pull request by ashutosh017**

### CODE REVIEW

**Comment by ashutosh017** [comment]
wo render ke backend ki link uncomment kr lena

**Comment by retrogtx** [comment]
this is cool, but if more than 2 users join the same room, how are they going to differentiate between which message is sent by whom?

there isn't a section to add temporary names in your feature set. it was 2 people only for a reason..

**Comment by ashutosh017** [comment]
> this is cool, but if more than 2 users join the same room, how are they going to differentiate between which message is sent by whom?
> 
> there isn't a section to add temporary names in your feature set. it was 2 people only for a reason..

you can thnk of it as anonymous chat room or if u say I will try to add temporary name section

**Comment by retrogtx** [comment]
> > this is cool, but if more than 2 users join the same room, how are they going to differentiate between which message is sent by whom?
> > 
> > there isn't a section to add temporary names in your feature set. it was 2 people only for a reason..
> 
> you can thnk of it as anonymous chat room or if u say I will try to add temporary name section
> 

I'll soon try to add two different pop ups that will ask the user to create a normal chat vs a group chat, if they choose group chat then it'll ask for their names

**Pull request merged**
